/* auto-generated by OHOS-RS */
/* eslint-disable */

export declare function startWarpMain(filesDir: string, cacheDir: string, tempDir: string, currentDir: string): void;
export declare function registerServiceBridge(): void;
export declare function setAbilityContext(context: object): void;
export declare function onTouchEvent(touchType: number, x: number, y: number): void;
export declare function onKeyEvent(keyCode: number, keyAction: number, modifierState: number): void;
export declare function onMouseEvent(mouseAction: number, mouseButton: number, x: number, y: number): void;
export declare function onWheelEvent(deltaX: number, deltaY: number): void;
