/* auto-generated by OHOS-RS */
/* eslint-disable */

/**
 * Native module session/render contract.
 *
 * These are the ArkTS-visible exports of libcore.so's `#[ability]` module
 * (the `openharmony_ability_mod` generated by openharmony-ability-derive).
 * NativeAbility loads this library by moduleName "core" and drives the
 * module lifecycle via these functions.
 */

export declare function render(slot: object, renderOwner: string): void;
export declare function disposeRender(renderOwner: string): void;
export declare function disposeAllRenders(): void;
export declare function init(
  bindings: object,
  bridgeOwner: string,
  context: object | null,
): object;
export declare function disposeBridge(bridgeOwner: string): void;
export declare function onBackPressIntercept(): boolean;
export declare function onBridgeLifecycle(kind: string): void;
